### ISSUE TITLE
Rubrics

### ISSUE THREAD

**Issue by sydbross** [ALHCSB/web-app#18]

**Comment by labr0110** [comment]
UX Rubric Review

Details: 2 points
Brand Identity: 3 points
Content: 2 points
Image Quality: 3 points
Design/Creativity: 2 points
Teamwork: 2 points
Research: 2 points

Total: 16/21

@thomasjbradley

**Comment by sydbross** [comment]
![rubric-01](https://user-images.githubusercontent.com/16649581/36224552-fdcb5e56-1195-11e8-8d56-f63b5915b22e.png)
![rubric-02](https://user-images.githubusercontent.com/16649581/36224554-fdd9f178-1195-11e8-9040-0d575bb8a71f.png)
