### ISSUE TITLE
Sprint 6 review

### ISSUE THREAD

**Issue by sydbross** [ALHCSB/web-app#38]
Everything was completed with help from Thomas, now onto combining all our pages together. A good sprint.

**Comment by hcapson** [comment]
I finished coding all the middle sections so they are ready to be combined to create the whole app. Only thing i didn't finish was the like buttons because I couldn't figure it out on my own.

**Comment by labr0110** [comment]
I finished coding the website in class and after class. We completed the pages and linked them all together to make a website. We also made sure that it was responsive and looked good on all screen sizes.
