### ISSUE TITLE
Sprint Two Review

### ISSUE THREAD

**Issue by labr0110** [ALHCSB/web-app#9]
Overall, we are on track. The only thing that is incomplete is to determine the app name and finalizing the logo. Otherwise, we have a good rough of the UX and we determined the key features and target audience.

@thomasjbradley

**Comment by sydbross** [comment]
We are well on our way to creating a successful app. I have yet to complete the logo and app name but we are aiming to get that done in the coming sprint. UX looks great, key features are coming along strongly, and the target audience is in place

**Comment by hcapson** [comment]
I succeeded well in sprint 2. I finished rough sketches for the app, and started the UX in XD. We did miss a few things that we planned for the sprint, but we are still on track.

**Comment by labr0110** [comment]
I wasn't there last week during class which was a bit confusing at first, but once Hayley and Sydney explained my tasks, I was able to complete what I had to do. I met up with Hayley to talk about the key features and target audience, and I came up with a few potential app names.

Our team works really well together, we know what needs to be done and we all did our part.

**Comment by thomasjbradley** [comment]
Your Sprint reviews are well done—thanks.

---

The Sprint 2 Issues are nicely detailed, but many of the todo lists are not checked off even though the Issues are closed.
